apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"us.svc.cluster.local": ["23.99.151.229"]}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  us.svc.cluster.local.server: |
    us.svc.cluster.local:53 {
        errors
        cache 30
        forward . 23.99.151.229
    }
    eu.svc.cluster.local:53 {
        errors
        cache 30
        forward . 13.79.26.142
    }    