apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"us.svc.cluster.local": ["11.240.0.97"]}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  us.svc.cluster.local.server: |
    us.svc.cluster.local:53 {
        errors
        cache 30
        forward . 11.240.0.97
    }